name: 🎮 Bug with FreePlay Launcher
description: For issues and bugs with the FreePlay desktop launcher.
labels: [app, bug]
type: 'bug'
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following
      options:
        - label: I checked the [existing issues](https://github.com/gautamcoder235/FreePlay-Minecraft-Launcher/issues?q=is%3Aissue) for duplicate problems
          required: true
        - label: I have ensured my FreePlay Launcher installation is up to date
          required: true
  - type: input
    id: version
    attributes:
      label: What version of FreePlay Launcher are you using?
      description: e.g. v1.0.1
    validations:
      required: true
  - type: dropdown
    id: oses
    attributes:
      label: Operating System
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Linux
        - macOS
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Include screenshots or error logs if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open launcher
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context & logs
      description: Add any error logs, crash reports, or other context here.
    validations:
      required: false
